### ISSUE TITLE
Change icon for for Dracula theme in the FreeCAD preference pack?

### ISSUE THREAD

**Issue by luzpaz** [dracula/freecad#7]
The [dracula theme page](https://draculatheme.com/freecad) shows 

![Screenshot_20220714_155301](https://user-images.githubusercontent.com/4140247/179071489-c23bea7d-c098-4e82-964a-7b7c0d7dbf8c.png). 

The current preference pack looks like:
![image](https://user-images.githubusercontent.com/4140247/179071574-e715d4d5-5c47-4677-af43-84ccf7758b1b.png)

Perhaps using that icon for the preference pack makes sense?

CC @Chrismettal

**Comment by Chrismettal** [comment]
I was hoping to start a trend of showing some defining colors of the theme, right in the icon, in a way that you will get all the required information by just scrolling through the addon manager. That's why the icons of both packs look so similar, just with the colors swapped to ones from the themes palette.

I don't mind changing it to a more appropriate logo though, if you think that idea doesn't catch @luzpaz!

I also thought the original Dracula icon could be more appropriate as well:
https://draculatheme.com/static/icons/used/pack-1/045-dracula.svg

**Comment by luzpaz** [comment]
> I was hoping to start a trend of showing some defining colors of the theme, right in the icon

Totally makes sense!
