### ISSUE TITLE
The spreadsheet's text color should be white.

### ISSUE THREAD

**Issue by megabitsenmzq** [dracula/freecad#9]
The spreadsheet's text color should be white.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/5499507/206831580-0068fdd6-17d3-4057-92c9-5eac7c8656f2.png">

The current text color in a spreadsheet has black color. I have to change it manually every time. Do we have a solution for this? (^-^)

**Comment by Chrismettal** [comment]
IIRC the text colors can't be set via stylesheets nor preference packs as they are fully driven from the code. Otherwise you wouldn't be able to choose colors in the spreadsheet at all.

Also making the stylesheet choose a new default color for the spreadsheet might be problematic. What would we do if we change the stylesheet on a table that is already filled out with a readable color? We would need to detect the now unreadable color and swap that one over, effectively touching stuff potentially manually set for a reason..

**Comment by megabitsenmzq** [comment]
Got it! Thank you for answering my question.
